version: "3.7"

services:
  api:
    build: .
    command: air -c .air.toml
    volumes:
      - ./:/usr/app
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
